-- Nexora Mobile - Supabase/PostgreSQL starter schema
-- Run this in Supabase SQL Editor when moving from LocalStorage demo mode to shared multi-device mode.

create table if not exists products (
  id text primary key,
  brand text not null,
  name text not null,
  series text,
  category text not null,
  ram jsonb default '[]'::jsonb,
  storage jsonb default '[]'::jsonb,
  colors jsonb default '[]'::jsonb,
  price numeric not null default 0,
  stock integer not null default 0,
  warranty_months integer not null default 12,
  featured boolean default false,
  created_at timestamptz default now()
);

create table if not exists orders (
  id text primary key,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  township text not null,
  order_status text not null default 'Pending',
  payment_method text not null,
  payment_status text not null default 'Pending Verification',
  payment_proof_url text,
  delivery_fee numeric not null default 0,
  delivery_eta text,
  rider_name text,
  rider_phone text,
  delivery_notes text,
  total numeric not null default 0,
  created_at timestamptz default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id text references orders(id) on delete cascade,
  product_id text references products(id),
  qty integer not null default 1,
  ram text,
  storage text,
  color text,
  unit_price numeric not null default 0
);

create table if not exists pos_sales (
  id text primary key,
  payment_method text not null,
  total numeric not null default 0,
  created_at timestamptz default now()
);

create table if not exists pos_sale_items (
  id bigint generated by default as identity primary key,
  sale_id text references pos_sales(id) on delete cascade,
  product_id text references products(id),
  qty integer not null default 1,
  unit_price numeric not null default 0
);

create table if not exists devices (
  imei text primary key,
  product_id text references products(id),
  order_id text,
  pos_sale_id text,
  sold_at timestamptz,
  warranty_expiry timestamptz,
  status text default 'Available'
);

create table if not exists warranty_claims (
  id text primary key,
  imei text references devices(imei),
  issue text,
  status text default 'Submitted',
  created_at timestamptz default now()
);

create table if not exists delivery_zones (
  id bigint generated by default as identity primary key,
  township text unique not null,
  fee numeric not null default 0,
  eta text
);

create table if not exists stock_movements (
  id bigint generated by default as identity primary key,
  product_id text references products(id),
  movement_type text not null,
  quantity integer not null,
  reference_id text,
  note text,
  created_at timestamptz default now()
);

create table if not exists return_requests (
  id text primary key,
  order_id text references orders(id),
  type text not null,
  reason text,
  status text default 'Pending',
  created_at timestamptz default now()
);


-- Final project additions
create table if not exists payment_settings (
  id bigint generated by default as identity primary key,
  provider text unique not null,
  phone text,
  account_name text,
  active boolean default true,
  updated_at timestamptz default now()
);

create table if not exists product_variants (
  id text primary key,
  product_id text references products(id) on delete cascade,
  ram text,
  storage text,
  color text,
  price numeric not null default 0,
  stock integer not null default 0
);

alter table products
  add column if not exists discount_type text default 'none',
  add column if not exists discount_value numeric default 0,
  add column if not exists promo_active boolean default false,
  add column if not exists gift_name text,
  add column if not exists gift_qty integer default 0,
  add column if not exists gift_active boolean default false;


create table if not exists expenses (
  id text primary key,
  name text not null,
  category text not null,
  amount numeric not null default 0,
  expense_date date not null,
  note text,
  created_at timestamptz default now()
);
